# 라이브러리 설치
## 터미널 pip install numpy
## 셀: %pip install numpy
# 라이브러리 제거
## 터미널 pip uninstall numpy
## 셀: %pip uninstall numpy
# 실행
## py: F5 (사용자 등록)
## ipynb: Shift + Enter

In [4]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
# 외부 라이브러리 설치 후 import 해야한다.
import numpy as np

In [ ]:
# 참고
# * = 모든 것
from numpy import *

In [8]:
# 리스트의 항목에 2 곱하기
# 예) [1, 2,3, 4] -> [2, 4, 6, 8]
# 리스트 연산 - > 반복문 필요
list_data = [1, 2, 3, 4]
result_list = []
for item in list_data:
    result_list.append(item * 2)
print(result_list)

[2, 4, 6, 8]


In [10]:
# 배열 연산 -> 반복문 불필요
# 백터화 연산
array_data = np.array([1, 2, 3, 4])
result_array = array_data * 2
print(result_array)
result_array

[2 4 6 8]


array([2, 4, 6, 8])

In [11]:
# 리스트 vs 배열 성능 비교
import time

In [16]:
# 리스트를 사용한 연산
start_time = time.time()
# 1970-01-01 00:00:00 기준으로 초 단위로 시간을 표현한 것
print(start_time)
# 0, 1, 2, 3, ... , 999999] 형태의 리스트 생성
python_list = list(range(1000000))
restult_list = [x * 2 for x in python_list]
# print(restult_list)
list_time = time.time() - start_time
print(f"리스트 연산 시간: {list_time:.4f}초")

1782355647.7233593
리스트 연산 시간: 0.1729초


In [18]:
# NumPy 배열을 사용한 연산
start_time = time.time()
print(start_time)
numpy_array = np.arange(1000000)
result_array = numpy_array * 2
print(result_array)
numpy_time = time.time() - start_time
print(f'NumPy 연산시간: {numpy_time:.4f}초')
print(f'속도 개선: {list_time/numpy_time:.1f}배')

1782356032.5971184
[      0       2       4 ... 1999994 1999996 1999998]
NumPy 연산시간: 0.2640초
속도 개선: 0.7배
