# 최신 표준: Generator 객체 사용법 (추천)

In [2]:
import numpy as np

# 1. 최신 표준 Generator 생성
rng = np.random.default_rng()
print(rng)

Generator(PCG64)


## rng.integers(low, high, size): 정수 무작위 추출

In [3]:
# 1 이상 46 미만(1~45)의 숫자 중 6개를 1차원 배열로 추출
lotto = rng.integers(1, 46, size=6)
print(lotto)  # 예: [12 45  3 24 18  7]

# 0 이상 10 미만의 정수로 채워진 2행 3열짜리 배열 생성
matrix_int = rng.integers(0, 10, size=(2, 3))
print(matrix_int)

[ 8 30  5 12 39 22]
[[4 2 8]
 [7 6 3]]


## rng.random(size): 0.0 이상 1.0 미만의 실수 추출

In [7]:
# 0.0 ~ 1.0 사이의 실수로 채워진 3행 2열 배열 생성
matrix_float = rng.random((3, 2))
print(matrix_float)

[[0.79120094 0.41071406]
 [0.08933712 0.12791648]
 [0.61370186 0.48598712]]


## rng.choice(a, size, replace): 샘플 추출 (복원/비복원)

In [8]:
items = ['Apple', 'Banana', 'Orange', 'Grape']

# 중복을 허용하여 2개 선택 (기본값: replace=True)
print(rng.choice(items, size=2))

# 중복 없이 3개 선택 (비복원 추출)
print(rng.choice(items, size=3, replace=False))

['Banana' 'Grape']
['Orange' 'Apple' 'Banana']


## rng.shuffle(x)/rng.permutation(x): 무작위 무작위 셔플

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.shuffle(arr)
print("원본:", arr)       # 원본이 변경
print("셔플본:", shuffled) # 변환값 없음(None)

원본: [1 5 2 3 4]
셔플본: None


In [11]:
arr = np.array([1, 2, 3, 4, 5])

shuffled = rng.permutation(arr)
print("원본:", arr)       # [1, 2, 3, 4, 5] 그대로 유지
print("셔플본:", shuffled) # 무작위 뒤섞인 배열

원본: [1 2 3 4 5]
셔플본: [2 5 1 3 4]


# 확률 분포 기반 난수 생성 (통계·머신러닝 필수)

## rng.normal(loc, scale, size): 정규 분포 (Gaussian)

In [14]:
# 평균 0, 표준편차 1인 표준정규분포를 따르는 데이터 10,000개 생성
normal_data = rng.normal(loc=0.0, scale=1.0, size=10000)
print(normal_data)

[ 0.93569136  2.44183824 -1.89747327 ...  0.42532504 -0.52056192
  0.40460113]


## rng.uniform(low, high, size): 균등 분포 (Uniform)

In [15]:
# 10.0부터 20.0 사이에서 균등한 확률로 5개 추출
uniform_data = rng.uniform(10.0, 20.0, size=5)
print(uniform_data)

[17.82443772 15.14984353 18.76706215 16.26683855 18.5890876 ]
