# 데이터 복제

## 1. 넘파이(NumPy) 2차원 배열의 복제

In [9]:
import numpy as np
import copy

# 2차원 배열 생성
arr_org = np.array([[1, 2], [3, 4]])
print(arr_org)

[[1 2]
 [3 4]]


In [4]:
# 넘파이 자체 copy() 메서드 사용
arr_copy = arr_org.copy()
print(arr_copy)
ref_copy = arr_copy
print(arr_copy)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [ ]:
# 데이터 수정
arr_copy[0, 0] = 99
ref_copy[1, 1] = 50

print(arr_org)
print(arr_copy)
print(ref_copy)

[[1 2]
 [3 4]]
[[99  2]
 [ 3 50]]
[[99  2]
 [ 3 50]]


## 2. 딕셔너리(Dictionary)의 복제 (★주의 필요)

In [6]:
# 2차원 구조의 중첩 딕셔너리
dict_org = {
    'group1': {'name': '김철수', 'age': 25}
}

print(dict_org)

{'group1': {'name': '김철수', 'age': 25}}


In [13]:
# 깊은 복사
dict_copy = copy.deepcopy(dict_org)

# 얕은 복사
# 딕셔너리 자체 copy() 사용
dict_ref_copy = dict_org.copy()

# 데이터 수정
dict_copy['group1']['age'] = 30
dict_ref_copy['group1']['name'] = '한오리'

In [14]:
# 출력
print(dict_org)
print(dict_copy)
print(dict_ref_copy)

{'group1': {'name': '한오리', 'age': 30}}
{'group1': {'name': '김철수', 'age': 30}}
{'group1': {'name': '한오리', 'age': 30}}
