In [2]:
# 배열의 연산과 변형
import numpy as np

# 배열 생성
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [3]:
## 벡터화 연산(Vectorized Operations)
arr + 2

array([3, 4, 5, 6])

In [4]:
arr * 2

array([2, 4, 6, 8])

In [5]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [6]:
# 반복
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [7]:
arr1 = np.arange(5, 9)
arr1

array([5, 6, 7, 8])

In [8]:
arr + arr1

array([ 6,  8, 10, 12])

In [9]:
arr * arr1

array([ 5, 12, 21, 32])

In [10]:
list = [1, 2, 3, 4]
list1 = [5, 6, 7, 8]

In [11]:
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

# 주요 산술 연산 함수

In [ ]:
# 제곱
print(np.square(arr))

# 제곱근(루트)
print(np.sqrt(arr))

# exp(지수승)
print(np.exp(arr)) 

# log
print(np.log(arr))   

[ 1  4  9 16]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


## 배열 연산 함수들

In [ ]:
# 더하기
print(np.add(arr, arr1)) 

# 합계
print(np.sum(arr)) 

# 누적합
print(np.cumsum(arr)) 

[ 6  8 10 12]
10
[ 1  3  6 10]


In [ ]:
### 3. 통계 함수들

In [16]:
# 평균
'''
(1 + 2 + 3 + 4)/4 = 2.5
'''
print(np.mean(arr))

#분산
'''
평균: 2.5
편차: -1.5, -0.5, 0.5, 1.5
편차의 제곱; 2.25, 0.25, 0.25, 2.25
분산: (2.15+0.25+0.25+2.25)/4 = 1.25
'''
print(np.var(arr))

# 표준편차(Standard Deviation)
# 표준편차 -> 분산의 제곱근: 루트1.25 -> 1.118033988749895
print(np.std(arr))

# 최솟값
print(np.min(arr))

# 최댓값
print(np.max(arr))

# 최솟값의 인덱스
print(np.argmin(arr))

# 최댓값의 인덱스
print(np.argmax(arr))

2.5
1.25
1.118033988749895
1
4
0
3


## 배열의 변형(Transformation)
### 1. 축 변환: 배열.transpose()

In [21]:
# 2차원 배열의 축 변환
arr = np.arange(10).reshape(2, 5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
# 2차원 배열의 축 변환
# (2, 5) -> (5, 2)
print(arr.transpose())

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [ ]:
# 3차원 배열 생성
# reshape(면, 행, 열)
arr3d = np.arange(27).reshape(3, 3, 3)
print(arr3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
# 3차원 배열의 축 변환
# (0, 1, 2) -> (1, 0, 2)
# 1: 1번 축에있던 '행'을 새로운 배열의 0번 축(연)으로
# 0: 0번 축에있던 '면'을 새오룬 배열의 1번 축(행)으로
# 2 2번 축에있던 '열'은 변홤없이 그대로 '2번 축(열)로
print(arr3d.transpose(1, 0, 2))

[[[ 0  1  2]
  [ 9 10 11]
  [18 19 20]]

 [[ 3  4  5]
  [12 13 14]
  [21 22 23]]

 [[ 6  7  8]
  [15 16 17]
  [24 25 26]]]


## 고급 연산 기법
### 브로드캐스팅
- shape(모양)가 다른 다차원 배열 또는 스칼라 값 사이에서 연산이 가능하게 만들어 주는 기능

In [24]:
# 2차원 배열과 1차원 배열의 연산
arr_2d = np.array([[1,2,3], [4,5,6]])
arr_1d = np.array([10,20,30])

result = arr_2d + arr_1d
print(result)

[[11 22 33]
 [14 25 36]]


In [25]:
# 축 지정 연산
# 열 방향 합계 (axis = 0)
print(np.sum(arr_2d, axis=0))
# 행 방향 합계 (axis = 1)
print(np.sum(arr_2d, axis=1))

# 전체 합계
print(np.sum(arr_2d))

[5 7 9]
[ 6 15]
21


### 조건부 연산

In [27]:
# 배열 생성
arr = np.array([1, -2, 3, -4, 5])

# 절댓값: 양수화
print(np.abs(arr))

# 조건에 따른 연산: np.where(조건식, 참, 거짓)
result = np.where(arr > 0, arr, 0)
print(result)

[1 2 3 4 5]
[1 0 3 0 5]


## 실무 활용 예시
### 정규화(Normalization)

In [ ]:
# 배열 생성
data = np.array([10,20,30,40,50])

# (data - min) / (min-max) 정규화
'''
([10,20,30,40,50] - 10) / (50 -10)
([10,20,30,40,50] - 10) / 40
([0,10,20,30,40]) / 40
[0.   0.25 0.5  0.75 1.  ]
'''
normalized = (data - np.min(data)) / (np.max(data) - np.min(data))
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
# Z-SCORE 정규환
z_score = (data - np.mean(data)) / np.std(data)
print(z_score)

## 이동평균 계산

In [ ]:
# 배열 생성
prices = np.array([100, 102, 98, 105, 103, 99, 101])

# 3일 이동평균 함수 생성
# np.convolve(배열, 필터, mode): 합성곱
# np.ones(window)/window
# np.ones(3)/3
# [1.,1.,1.]/3
# [1/3,1/3,1/3]
# [0.333,0.333,0.333]
filter_var = np.ones(3)/3
print(filter_var)
'''
[100, 102, 98, 105, 103, 99, 101]
[1/3,1/3,1/3]
100 * 1/3 + 102 * 1/3 + 98 * 1/3
(100 + 102 + 98) * 1/3
300 * 1/3
100.0

[100, 102, 98, 105, 103, 99, 101]
102 * 1/3 + 98 * 1/3 + 105 * 1/3
(102 + 98 + 105) * 1/3
305 * 1/3
101.66666667
'''
def moving_average(data, window):
    return np.convolve(data, np.ones(window)/window, mode='valid')

# 함수 호출
ma_3 = moving_average(prices, 3)
print(ma_3)

[0.33333333 0.33333333 0.33333333]
[100.         101.66666667 102.         102.33333333 101.        ]
